### ISSUE TITLE
Suggest: link to publication and/or publish

### ISSUE THREAD

**Issue by richelbilderbeek** [OchoaLab/simtrait#1]
Dear simtrait maintainers,

A few months ago I was searching the literature for GWAS dataset simulators (such as simtrait) and I have a list of twenty of such tools. Today I stumbled upon simtrait by accident and this appears to be the best tool I was looking for!

What I hope is that future people like me can find simtrait easier. For example, I have searched Google Scholar and Duck-duck-go-ed reasonably extensively.

If there is already an article out (that I also overlooked :-/ ), I suggest to link to it in the README.

Cheers, Richel

**Comment by alexviiia** [comment]
Hi Richel!  Unfortunately there's no article out yet (hopefully soon).  For now, there is a slightly outdated preprint which describes the main simulation model and algorithm (overlaps with the vignette, which is currently probably the best current source):

https://www.biorxiv.org/content/10.1101/858399v1

I'll leave this issue open until an updated and more complete reference preprint is available.

**Comment by richelbilderbeek** [comment]
Cool, awesome to find the article, thanks!

**Comment by alexviiia** [comment]
Forgot I added biorxiv link to DESCRIPTION in last commit, 0ef34a4.  The link will be updated there in the future.
